services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warframe-todo-tracker
    image: warframe-todo-tracker:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - PASSWORD=${PASSWORD:-}
      - AUTH_HASH=${AUTH_HASH:-}
    volumes:
      - ./data:/app/data
    labels:
      - "app=warframe-todo-tracker"
      - "stack=warframe"
